### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by nforst** [SvSys/vertretungsplan-java#1]
Hey,

besitzt du den Source code von den ganzen Dependencys, weil ich hab jetzt schon 20 Ordner an Source code und immer kommt nh Fehlermeldung weil noch ein Source code hinzugefügt werden muss muss es halt ohne Maven machen.

**Comment by kingjan1999** [comment]
Hey,

danke dass du mein Projekt nutzen willst!
Um deine Frage zu beantworten: Es sollte natürlich möglich sein, das ganze auch ohne Maven zum laufen zu bringen, gerade weil die Konfiguration ja eher simpel ist:

Im Wesentlichen musst du die Abhängigkeiten (zur Compile-Zeit ist das ja [jsoup](https://jsoup.org/packages/jsoup-1.11.3.jar), [gson](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar) und [commons-beanutils](http://central.maven.org/maven2/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar)) anders einbinden, was im Regelfall ja darauf hinaus laufen sollte die Jar-Dateien von den Projekt-Homepages runterzuladen (die Links führen unmittelbar auf die Dateien) und in den Classpath einzubinden (wie letzteres genau geht ist ja IIRC IDE abhängig).


Sollte allerdings das Ziel sein, das habe ich nicht ganz verstanden, den ganzen Source-Code der einzelnen Projekte mit in dein Projekt einzubinden (also keine externen Abhängigkeiten außer dem JDK bestehen sollen, was ja eher ungewöhnlich ist), würde ich davon abraten. Auch deshalb weil die o.g. drei Abhängigkeiten ja wiederum Abhängigkeiten usw. haben. Das würde zu einer Menge an Code führen, die nicht mehr wartbar ist und für den Zweck hier völlig überdimensioniert erscheint.
